apiVersion: v1
kind: Service 
metadata:
  name: app
  namespace: diplom

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3003
      nodePort: 30036
      protocol: TCP
  selector:
    app: app
  externalIPs:
    - 158.160.86.191
    - 158.160.83.69
